services:
  db-ana:
    build:
      context: ./MySQL
      dockerfile: Dockerfile
    container_name: mysql-ana
    restart: always
    ports:
      - "3307:3306"
    volumes:
      - ./MySQL/data:/var/lib/mysql
    networks:
      - portafolio-network
    healthcheck:
      test: ["CMD", "mysql" ,"-u", "portafolio-user", "-pCVEfL3^9CjoRJ#db"]
      interval: 30s
      timeout: 10s
      retries: 5

  adminer-ana:
    image : adminer
    container_name: adminer-ana
    restart: always
    ports:
      - "8081:8080"
    networks:
      - portafolio-network

networks:
  portafolio-network:
    driver: bridge
    name : portafolio-network